### PR TITLE
Update views with verb validation and CSRF exemption removal

### LINKED ISSUE #23: Add CSRF token usage to endpoints
Currently all of the endpoints in `views.py` have the `@csrf_exempt` decorators in order to bypass the requirement in Django. However, for security purposes, we should implement CSRF tokens and remove the decorators.

### PR DESCRIPTION
**Pull request by jsteuver**
Formatting fixes, additional verb validation, and CSRF fixes (resolves #23) .

The server will automatically generate the CSRF token on signup or login and will return it in the HTTP response. This token should then be passed as a cookie for each subsequent request. This is often done automatically in browsers and testing tools, but below is a example of one in case it manually needs to be set _(just substitute whatever value the server returns)_:

`csrftoken=lFHNkqKQi5pUqHciqfSg9NSWulpzz5cELv8pvzhAsbTtWiuKTBoHFvbjvcxwdAD; Path=/; Expires=Sun, 20 Feb 2022 16:14:08 GMT;`

This branch should go through integration testing with the front-end before merging to make sure that the tokens are working as expected.

### CODE REVIEW

**Review by segeeslice — COMMENTED** [review]
Code looks good! Will need to test before approval obviously

**Comment by segeeslice** [comment]
Would you mind rebasing after #43 is merged so I can test this a bit easier?

**Comment by jsteuver** [comment]
> @jsteuver Would you mind rebasing after #43 is merged so I can test this a bit easier?

@segeeslice  Done.

**Comment by segeeslice** [comment]
@jsteuver works on front-end just fine, as far as I can tell!

**Review by segeeslice — APPROVED** [review]

**Pull request merged**
