### PR TITLE
User profile endpoint and serialization fixes

### LINKED ISSUE #28: Don't return password when sending user data
image

When logging in (and potentially other spots of receiving user data), the password hash is returned and should not be.

### PR DESCRIPTION
**Pull request by jsteuver**
All user profile functionality can now be accessed through `/user/{id}/profile`. A `GET` to this endpoint will retrieve profile information for the selected user and does not follow authentication. A `POST` to this endpoint will update the selected user, and requires the specified user to already be logged in.

Custom serializers were also added so we can return model data more effectively. As part of this, the password field, as well as other fields, have been removed from the returned model when querying for user information, which resolves #28 .

### CODE REVIEW

**Comment by segeeslice** [comment]
Code looks good! I'll approve once I get around to some basic integration testing

**Comment by jsteuver** [comment]
Forgot to mention that Django's REST framework needs to be installed in order to use the serializers.

`pip install djangorestframework`

I have added this to the dependency documentation.

**Comment by segeeslice** [comment]
@jsteuver there are merge conflicts too; probably best to rebase onto master again

**Comment by jsteuver** [comment]
@segeeslice Done.

**Comment by segeeslice** [comment]
@jsteuver Can we also update the [API docs](https://github.com/RobBoeckermann/Meetify/tree/master/docs/api_docs) with the changes?

**Comment by segeeslice** [comment]
Testing this a bit now, this is what I received:

image

I'm not sure we should return all this data under `User` when getting the profile. In my mind "account" (User) and "profile" data would be separated, that way not anyone can just get more private areas like email and username.

We're also missing a `description` field for the users' personal descriptions.

**Comment by segeeslice** [comment]
Thanks for the updates! So far so good. Looks like this now, as expected:

image

Looking into profile updates now

**Comment by segeeslice** [comment]
Updating works too! Just one small gimmick I can't get past regarding the `ProfilePic` field...

---

### Issue

**When I send an update**, I'm trying to change ProfilePic, sending it:

```
"https://thumbs.dreamstime.com/z/man-face-painting-tiger-28693711.jpg"
```

**When the server returns**, I get the following value back:

```
"/https%3A/thumbs.dreamstime.com/z/man-face-painting-tiger-28693711.jpg"
```
image

### Location

I've narrowed it down to this method in `Django/Meetify/appapi/users.py`: 

image

I think it's here because when I print `data` here, it appears formatted correctly, but when check the returned value it's garbled like I showed earlier. However, I don't know why it's doing this nor how to fix it.

---

Could you investigate what's happening here? I can help as needed.

**Comment by jsteuver** [comment]
> Could you investigate what's happening here?

Not sure what the exact issue is that is causing the garbled URL, but I imagine it has to do with us simply not using the Django ImageField correctly. I opened #35 to address this as it may be somewhat involved.

**Comment by segeeslice** [comment]
> I opened #35 to address this as it may be somewhat involved.

Perfect, then we can consider that a separate issue for now, which is probably a smart choice. Approving now

**Review by segeeslice — APPROVED** [review]

**Pull request merged**
